name: CubicWorlds
version: '1.0-SNAPSHOT'
main: me.zootsuitproductions.cubicworlds.CubicWorlds
api-version: 1.19
commands:
  createCubeWorld:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  slice:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  goBackToNormalWorld:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  addFace:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  rot:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  pasteWorld:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
  pastePErm:
    description: Copies and pastes a block selection
    usage: /copypaste <copy/paste>
